In [ ]:
import pandas as pd #Lectura de archivos pdf, excel.... tambien sirve para la lectura de datos para su analisis
import numpy as np #Manejo de arreglos
import matplotlib.pyplot as plt #Creacion de graficas con informacion detallada
import seaborn as sns #Creacion de graficas bonitas pero con la informacion Simple
from google.colab import files #Importacion de archivos

In [ ]:
archivo = files.upload() #Cargar el archivo de datos del pc a Colab

Saving athlete_events.csv to athlete_events.csv

In [ ]:
df_athletes_events= pd.read_csv('athlete_events.csv') #Crear una variable donde me lea la informacion del Dataset para luego ser usada, si el archivo esta dentro del Computador
df_athletes_events.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
print(df_athletes_events.shape)

(271116, 15)

In [ ]:
df_athletes_events= df_athletes_events.drop_duplicates()

In [ ]:
print(df_athletes_events.shape)

(269731, 15)

In [ ]:
import unicodedata
import re

def limpiar_dataframe(df):
    df_clean = df.copy()

    def limpiar_columna(col):
        # Quitar espacios extremos
        col = col.strip()
        # Convertir a minúsculas
        col = col.lower()
        # Quitar tildes
        col = unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8')
        # Reemplazar espacios por _
        col = col.replace(' ', '_')
        # Eliminar caracteres especiales (solo letras, números y _)
        col = re.sub(r'[^a-z0-9_]', '', col)
        # Reemplazar múltiples _ por uno solo
        col = re.sub(r'_+', '_', col)
        return col

    df_clean.columns = [limpiar_columna(col) for col in df_clean.columns]

    return df_clean

In [ ]:
print(df_athletes_events.isnull().sum())

ID             0
Name           0
Sex            0
Age         9315
Height     58814
Weight     61527
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     229959
dtype: int64

In [ ]:
df_athletes_events['Medal'] = df_athletes_events['Medal'].fillna('No Medal')
print("Valores nulos en la columna 'Medal' después del reemplazo:")
print(df_athletes_events['Medal'].isnull().sum())

Valores nulos en la columna 'Medal' después del reemplazo:
0

In [ ]:
df_athletes_events.isnull().sum()

ID            0
Name          0
Sex           0
Age        9315
Height    58814
Weight    61527
Team          0
NOC           0
Games         0
Year          0
Season        0
City          0
Sport         0
Event         0
Medal         0
dtype: int64

In [ ]:
df=pd.DataFrame(df_athletes_events)

In [ ]:
print(df['Height'].mean())

175.33895323752947

In [ ]:
df_athletes_events['Height'] = df_athletes_events['Height'].fillna(175)
print("Valores nulos en la columna 'Medal' después del reemplazo:")
print(df_athletes_events['Height'].isnull().sum())

Valores nulos en la columna 'Medal' después del reemplazo:
0

In [ ]:
df_athletes_events.isnull().sum()

ID            0
Name          0
Sex           0
Age        9315
Height        0
Weight    61527
Team          0
NOC           0
Games         0
Year          0
Season        0
City          0
Sport         0
Event         0
Medal         0
dtype: int64

In [ ]:
print(df['Weight'].mean())

70.70177806382202

In [ ]:
df_athletes_events['Weight'] = df_athletes_events['Weight'].fillna(70)
print("Valores nulos en la columna 'Weight' después del reemplazo:")
print(df_athletes_events['Weight'].isnull().sum())

Valores nulos en la columna 'Weight' después del reemplazo:
0

In [ ]:
df_athletes_events.isnull().sum()

ID           0
Name         0
Sex          0
Age       9315
Height       0
Weight       0
Team         0
NOC          0
Games        0
Year         0
Season       0
City         0
Sport        0
Event        0
Medal        0
dtype: int64

In [ ]:
print(df['Age'].mean())

25.454776204227084

In [ ]:
df_athletes_events['Age'] = df_athletes_events['Age'].fillna(25)
print("Valores nulos en la columna 'Age' después del reemplazo:")
print(df_athletes_events['Age'].isnull().sum())

Valores nulos en la columna 'Age' después del reemplazo:
0

In [ ]:
df_athletes_events.isnull().sum()

ID        0
Name      0
Sex       0
Age       0
Height    0
Weight    0
Team      0
NOC       0
Games     0
Year      0
Season    0
City      0
Sport     0
Event     0
Medal     0
dtype: int64

In [ ]:
df = df=pd.DataFrame(df_athletes_events)

1. Se procede con creación del primer df el cual lo llamamos TEAMS, el cual contiene el equipo y el NOC

In [ ]:
teams = (
    df[['Team','NOC']]
    .drop_duplicates()
    .reset_index(drop=True)
)

teams.insert(0, 'team_id', teams.index + 1)

In [ ]:
teams.head()

   team_id            Team  NOC
0        1           China  CHN
1        2         Denmark  DEN
2        3  Denmark/Sweden  DEN
3        4     Netherlands  NED
4        5   United States  USA

In [ ]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No Medal
2,3,Gunnar Nielsen Aaby,M,24.0,175.0,70.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,No Medal
3,4,Edgar Lindenau Aabye,M,34.0,175.0,70.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,No Medal

In [ ]:
teams.to_csv('equipos_Games.csv', index=False)

**2**. Se procede con creación del segundo  df el cual lo llamamos Atletas , el cual contiene el id de concursante, el nombre, sexo, edad, estatura y peso

In [ ]:
athletes = (
    df[['ID','Year',  'Name','Sex','Age','Height','Weight']]
    .drop_duplicates()  # ¡Solo usa ID para determinar unicidad!
    .reset_index(drop=True)
)

# Luego agregamos el athlete_id
athletes.insert(0, 'athlete_id', athletes.index + 1)

In [ ]:
athletes.head()

   athlete_id  ID  Year                      Name Sex   Age  Height  Weight
0           1   1  1992                 A Dijiang   M  24.0   180.0    80.0
1           2   2  2012                  A Lamusi   M  23.0   170.0    60.0
2           3   3  1920       Gunnar Nielsen Aaby   M  24.0   175.0    70.0
3           4   4  1900      Edgar Lindenau Aabye   M  34.0   175.0    70.0
4           5   5  1988  Christine Jacoba Aaftink   F  21.0   185.0    82.0

In [ ]:
athletes.to_csv('Athletes_Games.csv', index=False)

In [ ]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No Medal
2,3,Gunnar Nielsen Aaby,M,24.0,175.0,70.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,No Medal
3,4,Edgar Lindenau Aabye,M,34.0,175.0,70.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,No Medal

Se crea otra tabla que sea la edicion de los juegos

In [ ]:
Edition = (
    df[['Games','Year','Season','City']]
    .drop_duplicates()
    .reset_index(drop=True)
)

Edition.insert(0, 'edition_id', Edition.index + 1)

In [ ]:
Edition.head()

   edition_id        Games  Year  Season       City
0           1  1992 Summer  1992  Summer  Barcelona
1           2  2012 Summer  2012  Summer     London
2           3  1920 Summer  1920  Summer  Antwerpen
3           4  1900 Summer  1900  Summer      Paris
4           5  1988 Winter  1988  Winter    Calgary

In [ ]:
Edition.to_csv('Edition_Games.csv', index=False)

Se crea tabla de Competicion

In [ ]:
Competition = (
    df[['Sport','Event']]
    .drop_duplicates()
    .reset_index(drop=True)
)

Competition.insert(0, 'Competition_id', Competition.index + 1)

In [ ]:
Competition.head()

   Competition_id          Sport                             Event
0               1     Basketball       Basketball Men's Basketball
1               2           Judo      Judo Men's Extra-Lightweight
2               3       Football           Football Men's Football
3               4     Tug-Of-War       Tug-Of-War Men's Tug-Of-War
4               5  Speed Skating  Speed Skating Women's 500 metres

In [ ]:
Competition.to_csv('Competition_Games.csv', index=False)

Se crean ID Para relacionar en BD Mongo

In [ ]:
df = df.merge(athletes[['ID', 'Year', 'athlete_id']], on=['ID', 'Year'], how='left')
df = df.merge(teams[['Team','NOC','team_id']], on=['Team','NOC'], how='left')
df= df.merge(Edition[['Games','City','edition_id']], on= ['Games','City'], how = 'left')
df= df.merge(Competition[['Sport','Event','Competition_id']], on= ['Sport','Event'], how = 'left')

In [ ]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,athlete_id,team_id,edition_id,Competition_id
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No Medal,1,1,1,1
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No Medal,2,1,2,2
2,3,Gunnar Nielsen Aaby,M,24.0,175.0,70.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,No Medal,3,2,3,3
3,4,Edgar Lindenau Aabye,M,34.0,175.0,70.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,4,3,4,4
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,No Medal,5,4,5,5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269798 entries, 0 to 269797
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              269798 non-null  int64
 1   Name            269798 non-null  object
 2   Sex             269798 non-null  object
 3   Age             269798 non-null  float64
 4   Height          269798 non-null  float64
 5   Weight          269798 non-null  float64
 6   Team            269798 non-null  object
 7   NOC             269798 non-null  object
 8   Games           269798 non-null  object
 9   Year            269798 non-null  int64
 10  Season          269798 non-null  object
 11  City            269798 non-null  object
 12  Sport           269798 non-null  object
 13  Event           269798 non-null  object
 14  Medal           269798 non-null  object
 15  athlete_id      269798 non-null  int64
 16  team_id         269798 non-null  int64
 17  edition_id      269798 non-null  int64
 18  Competition_id  269798 non-null  int64
dtypes: float64(3), int64(6), object(10)
memory usage: 39.1+ MB

3. Se eliminan columnas extraidas del DF principal

In [ ]:
df_athletes_events = df.drop(columns=['ID','Team','NOC','Name','Sex','Age','Height','Weight','Year','Season','Games','City','Sport','Event'])

In [ ]:
df_athletes_events.head(20)

       Medal  athlete_id  team_id  edition_id  Competition_id
0   No Medal           1        1           1               1
1   No Medal           2        1           2               2
2   No Medal           3        2           3               3
3       Gold           4        3           4               4
4   No Medal           5        4           5               5
5   No Medal           5        4           5               6
6   No Medal           6        4           6               5
7   No Medal           6        4           6               6
8   No Medal           7        4           7               5
9   No Medal           7        4           7               6
10  No Medal           8        5           6               7
11  No Medal           8        5           6               8
12  No Medal           8        5           6               9
13  No Medal           8        5           6              10
14  No Medal           9        5           7               7
15  No Medal           9        5           7              11
16  No Medal           9        5           7               9
17  No Medal           9        5           7              10
18  No Medal          10        5           6               7
19  No Medal          10        5           6               8

In [ ]:
df_athletes_events['id_participacion'] = df_athletes_events.index + 1
df_athletes_events.head()

      Medal  athlete_id  team_id  edition_id  Competition_id  id_participacion
0  No Medal           1        1           1               1                 1
1  No Medal           2        1           2               2                 2
2  No Medal           3        2           3               3                 3
3      Gold           4        3           4               4                 4
4  No Medal           5        4           5               5                 5

In [ ]:
cols = ['id_participacion'] + [col for col in df_athletes_events.columns if col != 'id_participacion']
df_athletes_events = df_athletes_events[cols]
df_athletes_events.head()

   id_participacion     Medal  athlete_id  team_id  edition_id  Competition_id
0                 1  No Medal           1        1           1               1
1                 2  No Medal           2        1           2               2
2                 3  No Medal           3        2           3               3
3                 4      Gold           4        3           4               4
4                 5  No Medal           5        4           5               5

In [ ]:
df_athletes_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269798 entries, 0 to 269797
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_participacion  269798 non-null  int64
 1   Medal             269798 non-null  object
 2   athlete_id        269798 non-null  int64
 3   team_id           269798 non-null  int64
 4   edition_id        269798 non-null  int64
 5   Competition_id    269798 non-null  int64
dtypes: int64(5), object(1)
memory usage: 12.4+ MB

EL DF despues del Merge Limpio para la descarga y el manejo de MONGO

In [ ]:
DFATLETAS=df_athletes_events.to_csv('JJ.OO.csv',index=False)

Se exporta el DF principal y le damos un nuevo nombre

In [ ]:
df.to_csv('JuegosOlimpicos_Olimpycs.csv', index=False)

In [ ]:
num_duplicados = df_athletes_events.duplicated().sum()
print(f"Número de filas duplicadas: {num_duplicados}")

# Si quieres ver las filas duplicadas
duplicadas = df_athletes_events[df_athletes_events.duplicated()]
print("\nFilas duplicadas:")
print(duplicadas)

Número de filas duplicadas: 0

Filas duplicadas:
Empty DataFrame
Columns: [id_participacion, Medal, athlete_id, team_id, edition_id, Competition_id]
Index: []

In [ ]:
df.groupby("athlete_id").size().sort_values(ascending=False).head()

athlete_id
93905     15
157248    13
35517     12
165281    12
47081     12
dtype: int64